AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Immiwatch Express Entry Draw Checker - Monitors IRCC draws every 15 minutes

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket for storing draw data
  AirtableWebhookUrl:
    Type: String
    Description: Airtable webhook URL for notifications
    NoEcho: true

Resources:
  DrawCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/ee-draw-checker/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          S3_BUCKET: !Ref S3BucketName
          WEBHOOK_URL: !Ref AirtableWebhookUrl
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Enabled: true

Outputs:
  DrawCheckerFunction:
    Description: "Express Entry Draw Checker Lambda Function ARN"
    Value: !GetAtt DrawCheckerFunction.Arn
  DrawCheckerFunctionRole:
    Description: "Implicit IAM Role created for the draw checker function"
    Value: !GetAtt DrawCheckerFunctionRole.Arn 