name: Deploy Immiwatch Functions

on:
  push:
    branches:
      - main
    paths:
      - 'src/functions/ee-draw-checker/**'
      - 'template.yaml'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/functions/ee-draw-checker/**'
      - 'template.yaml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:  # Enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aws-sam-cli
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing src directory:"
          ls -la src/
          echo "Listing functions directory:"
          ls -la src/functions/
          echo "Listing ee-draw-checker directory:"
          ls -la src/functions/ee-draw-checker/
          
      - name: Clean SAM build
        run: |
          rm -rf .aws-sam
          
      - name: Build and deploy with SAM
        run: |
          sam build
          sam deploy --no-fail-on-empty-changeset \
            --stack-name immiwatch-functions \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              S3BucketName=${{ secrets.S3_BUCKET_NAME }} \
              AirtableWebhookUrl=${{ secrets.AIRTABLE_WEBHOOK_URL }} 